name: pn_env
channels:
  - conda-forge  
dependencies:
  - python>=3.10
  - mne
  - mne-bids>=0.9
  - numpy=1.21
  - pandas
  - scikit-learn
  - scipy
  - ipykernel
  - pytest
  - filtyterpy
  - fooof
  - scikit-optimize
  - xgboost
  - imbalanced-learn
